!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        102WqR1I-Budgets:
          path: dataset/102WqR1I-Budgets
          prefix: ncino
          standardFeature: true
          versions:
            Rel 2024_07 v1:
              modifiedDate: '2026-08-14 07:06:20'
        102WqR1I-Forms:
          path: dataset/102WqR1I-Forms
          prefix: ncino
          standardFeature: true
          versions:
            Rel 2024_07 v2:
              modifiedDate: '2026-08-14 07:06:20'
        102WqR1I-Collateral Types:
          path: dataset/102WqR1I-Collateral Types
          prefix: ncino
          standardFeature: true
          versions:
            Rel 2024_07 v1:
              modifiedDate: '2026-08-14 06:48:42'
        102WqR1I-Roles:
          path: dataset/102WqR1I-Roles
          prefix: ncino
          standardFeature: true
          versions:
            Rel 2024_07 v1:
              modifiedDate: '2026-08-14 06:48:42'
