!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        01tWsJ0Q-Rules Engine:
          path: dataset/01tWsJ0Q-Rules Engine
          prefix: ncino
          standardFeature: true
          versions:
            Rel 2024_07 v1:
              modifiedDate: '2026-09-01 10:58:46'
        01oTzM0I-Budgets-PT-21:
          path: dataset/01oTzM0I-Budgets-PT-21
          prefix: Regre
          standardFeature: true
          versions:
            '1.0':
              modifiedDate: '2026-09-01 10:59:12'
